### ISSUE TITLE
Por que tu namespace es el mio?

### ISSUE THREAD

**Issue by JuanCrg90** [azaroma/tip-calc#1]
![screen shot 2016-10-11 at 11 41 22 am](https://cloud.githubusercontent.com/assets/2718753/19279604/b2a22bec-8fa7-11e6-9497-38d8ca0ac7da.png)

**Comment by azaroma** [comment]
Es que un día tuve problemas y descargué tu código. Fue hace como tres
clases.

**Comment by JuanCrg90** [comment]
ok, solo no borres la carpeta git de la otra persona, puedes reemplazar el remote, así se conserva todo el histórico.
